<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC '-//Apple//DTD PLIST 1.0//EN' 'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist>
    <dict>
        <key>fileTypes</key>
        <array>
            <string>ucf</string>
            <string>UCF</string>
        </array>
        <key>name</key>
        <string>ucfconstraints</string>
        <key>patterns</key>
        <array>

            <dict>
                <key>name</key>
                <string>storage.type.ucfconstraints</string>
                <key>match</key>
                <string>\b(?i)(DEFAULT|CONFIG|NET|TIMESPEC|TIMEGRP|INST|AREA_GROUP|RANGE|TNM)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>support.function.ucfconstraints</string>
                <key>match</key>
                <string>\b(?i)(RAMS|FFS|FROM|TO|FROM-TO|FROM-THRU-TO|RISING|FALLING)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.ucfconstraints</string>
                <key>match</key>
                <string>\b(?i)(LOC|IOSTANDARD|TIG|TNM_NET|DRIVE|PERIOD|SLEW|PULLUP|PULLDOWN|STEPPING|CLOCK_DEDICATED_ROUTE|MAX_FANOUT|FILE|FLOAT|USE_RLOC|RLOC|RLOC_ORIGIN|RLOC_RANGE)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.ucfconstraints</string>
                <key>match</key>
                <string>\b(?i)(FALSE|TRUE|LVCMOS12|LVCMOS15|LVCMOS18|LVCMOS25|LVCMOS33|LVPECL_25|LVDCI_15|LVDCI_18|LVDS_25|LVDSEXT_25|LVDCI_25|LVDCI_DV2_15|LVDCI_DV2_18|LVDCI_DV2_25|SSTL15_DCI|SSTL15_T_DCI|SSTL15|DIFF_SSTL15|DIFF_SSTL15_T_DCI)\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(#).*$\n?</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(//).*$\n?</string>
                <key>name</key>
                <string>comment.line.double-slash</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>/\*</string>
                <key>end</key>
                <string>\*/</string>
                <key>name</key>
                <string>comment.block</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i)(\d+\s*(fs|ps|ns|us|ms|s)?)\b</string>
                <key>name</key>
                <string>constant.numeric.ucfconstraints</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(=|;|\|)</string>
                <key>name</key>
                <string>keyword.operator</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#strings</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>strings</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.systemverilog</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>"</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.systemverilog</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.double.systemverilog</string>
                    </dict>
                </array>
            </dict>
        </dict>

        <key>scopeName</key>
        <string>source.ucfconstraints</string>
        <key>uuid</key>
        <string>443130c7-cdc8-4a90-836c-a530d3b17266</string>
    </dict>
</plist>